name: kiota_dart_playground
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.7.0

dependencies:
  microsoft_kiota_bundle: ^0.1.0

dev_dependencies:
  lints: any
  test: ^1.26.3

dependency_overrides:
#  microsoft_kiota_serialization_json:
#    git:
#      url: https://github.com/ricardoboss/kiota-dart.git
#      path: packages/microsoft_kiota_serialization_json
#      ref: fixes/nested-intersection-type-serialization
