name: dart_multipart
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.7.0

dependencies:
  microsoft_kiota_bundle: ^0.1.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

dependency_overrides:
  microsoft_kiota_serialization_json:
    git:
      url: https://github.com/ricardoboss/kiota-dart.git
      path: packages/microsoft_kiota_serialization_json
      ref: fixes/nested-intersection-type-serialization
