openapi: 3.1.0
info:
  title: Workout API
  version: 1.0.0
servers:
  - url: https://api.example.com
paths:
  /workouts:
    get:
      summary: Get workout dates
      operationId: getWorkoutDates
      responses:
        '200':
          description: Successful response with workout dates
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkoutDatesResponse'
components:
  schemas:
    WorkoutDatesResponse:
      type: object
      properties:
        workout_dates:
          type: array
          description: Array of workout dates in ISO format
          items:
            type: string
            format: date-time
