openapi: 3.1.0
info:
  title: Workout API
  version: 1.0.0
servers:
  - url: https://api.example.com
paths:
  /workouts:
    get:
      summary: Get workout dates
      operationId: getWorkoutDates
      responses:
        '200':
          description: Successful response with workout dates
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkoutDatesResponse'
components:
  schemas:
    WorkoutDatesResponse:
      type: object
      properties:
        photo:
          type: string
          description: The base64-encoded contents of the file.
          format: base64url
          nullable: true
