openapi: 3.1.0
info:
  title: Playground API
  version: 1.0.0
paths:
  /user:
    get:
      summary: Get private/public user data
      responses:
        '200':
          description: Returns user data
          content:
            application/json:
              schema:
                oneOf:
                  - "$ref": "#/components/schemas/private-user"
                  - "$ref": "#/components/schemas/public-user"
                discriminator:
                  propertyName: view_type
                  mapping:
                    public: "#/components/schemas/public-user"
                    private: "#/components/schemas/private-user"
components:
  schemas:
    public-user:
      type: object
      properties:
        view_type:
          type: string
        login:
          type: string
        id:
          type: integer
          format: int64
        name:
          type: string
    private-user:
      type: object
      properties:
        view_type:
          type: string
        login:
          type: string
        id:
          type: integer
          format: int64
