openapi: 3.1.0
info:
  title: APIFiddle Sample Definition
  description: Example workspace
  version: 0.0.0
servers:
  - url: http://localhost:4183
paths:
  /data:
    post:
      operationId: getData
      summary: Get data
      responses:
        "200":
          description: The request was successful, and the server has returned the
            requested resource in the response body.
          content:
            application/json:
              schema:
                type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SampleData"
components:
  schemas:
    SampleData:
      type: object
      properties:
        busOrDog:
          anyOf:
            - type: object
              properties:
                numTires:
                  type: number
                color:
                  type: string
              required:
                - numTires
                - color
            - type: object
              properties:
                furColor:
                  type: string
                age:
                  type: number
              required:
                - furColor
                - age
      required:
        - busOrDog
      description: ""
